apply plugin: 'walle'

walle {
    // Specify the output path for channel packages
    apkOutputFolder = new File("${project.buildDir}/outputs/channels")
    // Customize the APK file name format for channel packages
    apkFileNameFormat = '${appName}-${packageName}-${channel}-${buildType}-v${versionName}-${versionCode}-${buildTime}.apk'
    // Channel configuration file
    channelFile = new File("${project.getProjectDir()}/channel")
}