apply plugin: 'com.xuexiang.xrouter'
apply plugin: 'kotlin-kapt'
//apply plugin: 'android-aspectjx'
apply plugin: 'com.xuexiang.xaop'

// Automatically add dependencies
configurations.each { configuration ->
    def dependencies = getProject().dependencies
    if (configuration.name == "implementation") {
        // Add X-Library dependencies to Project
        // XUI Framework
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xui))
        configuration.dependencies.add(dependencies.create(deps.androidx.appcompat))
        configuration.dependencies.add(dependencies.create(deps.androidx.recyclerview))
        configuration.dependencies.add(dependencies.create(deps.androidx.design))
        configuration.dependencies.add(dependencies.create(deps.glide))
        // XUtil Tool Class
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xutil_core))
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xutil_sub))
        // XAOP Aspect
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xaop_runtime))
        // XUpdate Version Update
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xupdate))
        // XHttp2
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xhttp2))
        configuration.dependencies.add(dependencies.create(deps.rxjava2))
        configuration.dependencies.add(dependencies.create(deps.rxandroid))
        configuration.dependencies.add(dependencies.create(deps.okhttp3))
        configuration.dependencies.add(dependencies.create(deps.gson))
        // XPage
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xpage_lib))
        // Page Routing
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xrouter_runtime))
    }

    if (configuration.name == "kapt") {
        // XPage
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xpage_compiler))
        // Page Routing
        configuration.dependencies.add(dependencies.create(deps.xlibrary.xrouter_compiler))
    }

    if (isNeedLeakcanary.toBoolean() && configuration.name == "debugImplementation") {
        // Memory leak detection
        configuration.dependencies.add(dependencies.create(deps.leakcanary))
    }
}

configurations.configureEach {
    resolutionStrategy.force deps.okhttp3
    // Always pull the latest build version
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

/*
aspectjx {
    // Modify package name here
    include 'com.idormy.sms.forwarder'
    // Exclude all class files and libraries (jar files) that contain `android.support` in the package path
    exclude 'android.support'
    // Remove kotlin related items to avoid compilation errors and improve speed
    exclude 'kotlin.jvm', 'kotlin.internal'
    exclude 'kotlinx.coroutines.internal', 'kotlinx.coroutines.android'
    exclude '*.jar', '*.aar', '*.so'
}
*/
